version: '3'
services:
  face-trace:
    image: "image_name:tag"
    ports:
      - 8000:8000
    environment:
      - APP_CONFIG_PATH=<path>/config.yaml
    volumes:
      - <host_path>:<docker_path>