detector_model:
  name: "FastMtcnn"
  model_path: null # pretrained model weights from /weights
  arguments:
    align: True
    expand_percentage: 0

embedding_model:
  name: "FaceNet512"
  model_path: null  # pretrained model weights from /weights

image_store:
  store_name: "ImageMetadataStore"
  builder_name: "ImageMetadataStoreBuilder"
  path: "<path/to/image_database>"
  arguments:
    vector_indexing: true
    indexing_kwargs:
      index_type: "Flat"
      metric: "inner_product"
      embedding_model: "FaceNet512"
    dumping_kwargs:
      interval: 120

